// Code generated by protoc-gen-go.
// source: pb/library.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/library.proto

It has these top-level messages:
	Document
	CreateDocumentRequest
	CreateDocumentReply
	FindDocumentsRequest
	FindDocumentsReply
	FindDocumentsByIdRequest
	FindDocumentsByIdReply
	ReplaceDocumentByIdRequest
	ReplaceDocumentByIdReply
	DeleteDocumentsByIdRequest
	DeleteDocumentsByIdReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateDocumentRequest struct {
	UserId   string    `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Document *Document `protobuf:"bytes,2,opt,name=document" json:"document,omitempty"`
}

func (m *CreateDocumentRequest) Reset()                    { *m = CreateDocumentRequest{} }
func (m *CreateDocumentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDocumentRequest) ProtoMessage()               {}
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateDocumentRequest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type CreateDocumentReply struct {
	Document *Document `protobuf:"bytes,1,opt,name=document" json:"document,omitempty"`
	Err      string    `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *CreateDocumentReply) Reset()                    { *m = CreateDocumentReply{} }
func (m *CreateDocumentReply) String() string            { return proto.CompactTextString(m) }
func (*CreateDocumentReply) ProtoMessage()               {}
func (*CreateDocumentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateDocumentReply) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type FindDocumentsRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *FindDocumentsRequest) Reset()                    { *m = FindDocumentsRequest{} }
func (m *FindDocumentsRequest) String() string            { return proto.CompactTextString(m) }
func (*FindDocumentsRequest) ProtoMessage()               {}
func (*FindDocumentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FindDocumentsReply struct {
	Documents []*Document `protobuf:"bytes,1,rep,name=documents" json:"documents,omitempty"`
	Err       string      `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *FindDocumentsReply) Reset()                    { *m = FindDocumentsReply{} }
func (m *FindDocumentsReply) String() string            { return proto.CompactTextString(m) }
func (*FindDocumentsReply) ProtoMessage()               {}
func (*FindDocumentsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindDocumentsReply) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type FindDocumentsByIdRequest struct {
	UserId string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (m *FindDocumentsByIdRequest) Reset()                    { *m = FindDocumentsByIdRequest{} }
func (m *FindDocumentsByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FindDocumentsByIdRequest) ProtoMessage()               {}
func (*FindDocumentsByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type FindDocumentsByIdReply struct {
	Documents []*Document `protobuf:"bytes,1,rep,name=documents" json:"documents,omitempty"`
	Err       string      `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *FindDocumentsByIdReply) Reset()                    { *m = FindDocumentsByIdReply{} }
func (m *FindDocumentsByIdReply) String() string            { return proto.CompactTextString(m) }
func (*FindDocumentsByIdReply) ProtoMessage()               {}
func (*FindDocumentsByIdReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FindDocumentsByIdReply) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type ReplaceDocumentByIdRequest struct {
	UserId   string    `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Id       string    `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Document *Document `protobuf:"bytes,3,opt,name=document" json:"document,omitempty"`
}

func (m *ReplaceDocumentByIdRequest) Reset()                    { *m = ReplaceDocumentByIdRequest{} }
func (m *ReplaceDocumentByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*ReplaceDocumentByIdRequest) ProtoMessage()               {}
func (*ReplaceDocumentByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReplaceDocumentByIdRequest) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type ReplaceDocumentByIdReply struct {
	Document *Document `protobuf:"bytes,1,opt,name=document" json:"document,omitempty"`
	Err      string    `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *ReplaceDocumentByIdReply) Reset()                    { *m = ReplaceDocumentByIdReply{} }
func (m *ReplaceDocumentByIdReply) String() string            { return proto.CompactTextString(m) }
func (*ReplaceDocumentByIdReply) ProtoMessage()               {}
func (*ReplaceDocumentByIdReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReplaceDocumentByIdReply) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DeleteDocumentsByIdRequest struct {
	UserId string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (m *DeleteDocumentsByIdRequest) Reset()                    { *m = DeleteDocumentsByIdRequest{} }
func (m *DeleteDocumentsByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentsByIdRequest) ProtoMessage()               {}
func (*DeleteDocumentsByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteDocumentsByIdReply struct {
	Documents []*Document `protobuf:"bytes,1,rep,name=documents" json:"documents,omitempty"`
	Err       string      `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteDocumentsByIdReply) Reset()                    { *m = DeleteDocumentsByIdReply{} }
func (m *DeleteDocumentsByIdReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteDocumentsByIdReply) ProtoMessage()               {}
func (*DeleteDocumentsByIdReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteDocumentsByIdReply) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

func init() {
	proto.RegisterType((*Document)(nil), "pb.Document")
	proto.RegisterType((*CreateDocumentRequest)(nil), "pb.CreateDocumentRequest")
	proto.RegisterType((*CreateDocumentReply)(nil), "pb.CreateDocumentReply")
	proto.RegisterType((*FindDocumentsRequest)(nil), "pb.FindDocumentsRequest")
	proto.RegisterType((*FindDocumentsReply)(nil), "pb.FindDocumentsReply")
	proto.RegisterType((*FindDocumentsByIdRequest)(nil), "pb.FindDocumentsByIdRequest")
	proto.RegisterType((*FindDocumentsByIdReply)(nil), "pb.FindDocumentsByIdReply")
	proto.RegisterType((*ReplaceDocumentByIdRequest)(nil), "pb.ReplaceDocumentByIdRequest")
	proto.RegisterType((*ReplaceDocumentByIdReply)(nil), "pb.ReplaceDocumentByIdReply")
	proto.RegisterType((*DeleteDocumentsByIdRequest)(nil), "pb.DeleteDocumentsByIdRequest")
	proto.RegisterType((*DeleteDocumentsByIdReply)(nil), "pb.DeleteDocumentsByIdReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Library service

type LibraryClient interface {
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentReply, error)
	FindDocuments(ctx context.Context, in *FindDocumentsRequest, opts ...grpc.CallOption) (*FindDocumentsReply, error)
	FindDocumentsById(ctx context.Context, in *FindDocumentsByIdRequest, opts ...grpc.CallOption) (*FindDocumentsByIdReply, error)
	ReplaceDocumentById(ctx context.Context, in *ReplaceDocumentByIdRequest, opts ...grpc.CallOption) (*ReplaceDocumentByIdReply, error)
	DeleteDocumentsById(ctx context.Context, in *DeleteDocumentsByIdRequest, opts ...grpc.CallOption) (*DeleteDocumentsByIdReply, error)
}

type libraryClient struct {
	cc *grpc.ClientConn
}

func NewLibraryClient(cc *grpc.ClientConn) LibraryClient {
	return &libraryClient{cc}
}

func (c *libraryClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentReply, error) {
	out := new(CreateDocumentReply)
	err := grpc.Invoke(ctx, "/pb.Library/CreateDocument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) FindDocuments(ctx context.Context, in *FindDocumentsRequest, opts ...grpc.CallOption) (*FindDocumentsReply, error) {
	out := new(FindDocumentsReply)
	err := grpc.Invoke(ctx, "/pb.Library/FindDocuments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) FindDocumentsById(ctx context.Context, in *FindDocumentsByIdRequest, opts ...grpc.CallOption) (*FindDocumentsByIdReply, error) {
	out := new(FindDocumentsByIdReply)
	err := grpc.Invoke(ctx, "/pb.Library/FindDocumentsById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) ReplaceDocumentById(ctx context.Context, in *ReplaceDocumentByIdRequest, opts ...grpc.CallOption) (*ReplaceDocumentByIdReply, error) {
	out := new(ReplaceDocumentByIdReply)
	err := grpc.Invoke(ctx, "/pb.Library/ReplaceDocumentById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) DeleteDocumentsById(ctx context.Context, in *DeleteDocumentsByIdRequest, opts ...grpc.CallOption) (*DeleteDocumentsByIdReply, error) {
	out := new(DeleteDocumentsByIdReply)
	err := grpc.Invoke(ctx, "/pb.Library/DeleteDocumentsById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Library service

type LibraryServer interface {
	CreateDocument(context.Context, *CreateDocumentRequest) (*CreateDocumentReply, error)
	FindDocuments(context.Context, *FindDocumentsRequest) (*FindDocumentsReply, error)
	FindDocumentsById(context.Context, *FindDocumentsByIdRequest) (*FindDocumentsByIdReply, error)
	ReplaceDocumentById(context.Context, *ReplaceDocumentByIdRequest) (*ReplaceDocumentByIdReply, error)
	DeleteDocumentsById(context.Context, *DeleteDocumentsByIdRequest) (*DeleteDocumentsByIdReply, error)
}

func RegisterLibraryServer(s *grpc.Server, srv LibraryServer) {
	s.RegisterService(&_Library_serviceDesc, srv)
}

func _Library_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Library/CreateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_FindDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).FindDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Library/FindDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).FindDocuments(ctx, req.(*FindDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_FindDocumentsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDocumentsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).FindDocumentsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Library/FindDocumentsById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).FindDocumentsById(ctx, req.(*FindDocumentsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_ReplaceDocumentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceDocumentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).ReplaceDocumentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Library/ReplaceDocumentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).ReplaceDocumentById(ctx, req.(*ReplaceDocumentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_DeleteDocumentsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).DeleteDocumentsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Library/DeleteDocumentsById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).DeleteDocumentsById(ctx, req.(*DeleteDocumentsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Library_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Library",
	HandlerType: (*LibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDocument",
			Handler:    _Library_CreateDocument_Handler,
		},
		{
			MethodName: "FindDocuments",
			Handler:    _Library_FindDocuments_Handler,
		},
		{
			MethodName: "FindDocumentsById",
			Handler:    _Library_FindDocumentsById_Handler,
		},
		{
			MethodName: "ReplaceDocumentById",
			Handler:    _Library_ReplaceDocumentById_Handler,
		},
		{
			MethodName: "DeleteDocumentsById",
			Handler:    _Library_DeleteDocumentsById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("pb/library.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x4e, 0xc2, 0x30,
	0x14, 0xc6, 0xd9, 0x96, 0xf0, 0xe7, 0xa8, 0x04, 0x8b, 0x42, 0x6d, 0x88, 0x31, 0xbd, 0x22, 0x5e,
	0x40, 0x82, 0x6f, 0x20, 0x88, 0x21, 0xd1, 0x18, 0x49, 0x24, 0xc6, 0x1b, 0xc3, 0x58, 0x2f, 0x96,
	0x20, 0x9b, 0xdd, 0xb8, 0xe0, 0x41, 0x7c, 0x5f, 0xdb, 0x95, 0x0d, 0x06, 0x1d, 0x18, 0x77, 0xd7,
	0xf6, 0x9c, 0xf3, 0xeb, 0xd9, 0xf9, 0xbe, 0x0e, 0x6a, 0xbe, 0xdd, 0x9d, 0xbb, 0x36, 0x9f, 0xf2,
	0x55, 0xc7, 0xe7, 0x5e, 0xe8, 0x21, 0xd3, 0xb7, 0xe9, 0x33, 0x94, 0x07, 0xde, 0x6c, 0xf9, 0xc5,
	0x16, 0x21, 0xaa, 0x82, 0xe9, 0x3a, 0xd8, 0xb8, 0x31, 0xda, 0x95, 0xb1, 0x58, 0xa1, 0x26, 0x94,
	0x96, 0x01, 0xe3, 0x9f, 0xe2, 0xd0, 0x8c, 0x0e, 0x8b, 0x72, 0x3b, 0x72, 0x10, 0x86, 0xd2, 0xcc,
	0x5b, 0x84, 0xa2, 0x06, 0x5b, 0x51, 0x20, 0xde, 0xd2, 0x0f, 0xb8, 0xec, 0x73, 0x36, 0x0d, 0x59,
	0x0c, 0x1d, 0xb3, 0xef, 0x25, 0x0b, 0xc2, 0x6d, 0x96, 0x91, 0x62, 0xb5, 0xa1, 0xec, 0xac, 0x73,
	0xa3, 0x5b, 0x4e, 0x7a, 0xa7, 0x1d, 0xdf, 0xee, 0x24, 0xf5, 0x49, 0x94, 0xbe, 0x42, 0x7d, 0x97,
	0xed, 0xcf, 0x57, 0x29, 0x80, 0x71, 0x08, 0x80, 0x6a, 0x60, 0x31, 0xce, 0xd7, 0xdf, 0x22, 0x97,
	0xb4, 0x0b, 0x17, 0x43, 0x77, 0xe1, 0xc4, 0xb9, 0xc1, 0xb1, 0x6e, 0xe9, 0x18, 0xd0, 0x4e, 0x81,
	0x6c, 0xe1, 0x16, 0x2a, 0xf1, 0x25, 0x81, 0x28, 0xb0, 0xf6, 0x7a, 0xd8, 0x84, 0x35, 0x4d, 0x3c,
	0x00, 0x4e, 0x31, 0xef, 0x57, 0x23, 0xe7, 0xe8, 0xd8, 0x04, 0xc6, 0x75, 0x02, 0x81, 0xb1, 0x24,
	0x46, 0x2c, 0xe9, 0x04, 0x1a, 0x1a, 0x4c, 0xfe, 0xf6, 0x3c, 0x20, 0x12, 0x33, 0x9d, 0x25, 0x73,
	0xff, 0x53, 0x83, 0xca, 0x4c, 0x66, 0x62, 0xa6, 0x6d, 0x99, 0xac, 0x83, 0x3a, 0x4f, 0x00, 0x6b,
	0x2f, 0xcc, 0x2b, 0xf6, 0x23, 0x90, 0x01, 0x9b, 0xb3, 0x8d, 0x7f, 0xfe, 0x3b, 0xe9, 0x77, 0xc0,
	0x5a, 0x50, 0xee, 0x59, 0xf7, 0x7e, 0x2c, 0x28, 0x3d, 0xa9, 0x37, 0x8a, 0x86, 0x50, 0x4d, 0xdb,
	0x1d, 0x5d, 0x49, 0x90, 0xf6, 0x79, 0x91, 0xa6, 0x2e, 0x24, 0xfa, 0xa1, 0x05, 0xd4, 0x87, 0xb3,
	0x94, 0x2f, 0x10, 0x96, 0xb9, 0x3a, 0xdb, 0x93, 0x86, 0x26, 0xa2, 0x20, 0x2f, 0x70, 0xbe, 0x67,
	0x2e, 0xd4, 0xda, 0x4b, 0xdf, 0x1a, 0x28, 0x21, 0x19, 0x51, 0x05, 0x7c, 0x83, 0xba, 0x46, 0x64,
	0x74, 0x2d, 0x8b, 0xb2, 0xed, 0x46, 0x5a, 0x99, 0xf1, 0x04, 0xab, 0x91, 0x46, 0x61, 0xb3, 0xc5,
	0x57, 0xd8, 0x2c, 0x4d, 0x69, 0xc1, 0x2e, 0x46, 0x3f, 0xcc, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x22, 0xa0, 0x6e, 0x44, 0x05, 0x00, 0x00,
}
